# Generated by Django 4.2.3 on 2023-08-10 21:38

import cloudinary.models
import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "chapter_profile_image",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="chapter",
                    ),
                ),
                ("institution", models.CharField(max_length=100)),
                (
                    "registration_fee",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("description", models.CharField(max_length=250)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Chapters",
            },
        ),
        migrations.CreateModel(
            name="ChapterRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Updated at"
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chapters.chapter",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "updated_at"),
                "abstract": False,
            },
        ),
    ]
