# Generated by Django 4.2.3 on 2023-08-22 20:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chapters", "0003_alter_chapterregister_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chapterregister",
            options={"verbose_name_plural": "Chapter Registers"},
        ),
    ]
