# Generated by Django 4.2.3 on 2023-08-27 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chapters", "0004_alter_chapterregister_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="chapter_admin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
