# Generated by Django 4.2.4 on 2023-08-23 11:34

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ("chapters", "0004_alter_chapterregister_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
