# Generated by Django 4.2.4 on 2023-08-27 14:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chapters", "0005_alter_chapter_chapter_admin"),
        ("chapters", "0005_alter_chapter_name"),
    ]

    operations = []
