# Generated by Django 4.2.4 on 2023-08-27 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chapters", "0007_chapterleadership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapterleadership",
            name="chapter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapter_leaders",
                to="chapters.chapter",
            ),
        ),
    ]
