# Generated by Django 4.2.4 on 2023-08-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chapters", "0008_alter_chapterleadership_chapter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="id",
            field=models.CharField(
                editable=False,
                max_length=255,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
