# Generated by Django 4.2.3 on 2023-08-10 21:38

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
