# Generated by Django 4.2.4 on 2023-08-16 11:32

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_remove_feed_feed_img_feed_poster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="status",
            field=models.CharField(
                choices=[
                    ("Approved", "Approved"),
                    ("Pending", "Pending"),
                    ("Rejected", "Rejected"),
                    ("Review", "Review"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
