# Generated by Django 4.2.4 on 2023-08-16 13:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "news",
            "0006_comment_like_post_delete_feed_like_post_comment_post_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="comments",
        ),
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
    ]
