# Generated by Django 4.2.4 on 2023-08-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0002_rename_name_feedback_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="title",
        ),
        migrations.AddField(
            model_name="feedback",
            name="rating",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                ],
                default=None,
                null=True,
            ),
        ),
    ]
