# Generated by Django 4.2.4 on 2023-08-28 12:27

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0004_alter_feedback_options_alter_feedback_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="attachment",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="feedback"
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="feedback_category",
            field=models.CharField(
                blank=True, default=None, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="origin",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="feedback",
            field=models.TextField(blank=True, null=True),
        ),
    ]
