# Generated by Django 4.2.4 on 2023-08-11 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ("user_module", "0004_remove_qualificationinfo_other_skills_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qualificationinfo",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qualification_info",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
