# Generated by Django 4.2.4 on 2023-08-13 13:28

import django.core.validators
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ("user_module", "0006_alter_educationinfo_institution_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educationinfo",
            name="graduation_year",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1984)],
                verbose_name="Year of Graduation",
            ),
        ),
    ]
