# Generated by Django 4.2.4 on 2023-08-14 18:47

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ("user_module", "0007_alter_educationinfo_graduation_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qualificationinfo",
            name="years_of_experience",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Total Years of Experience",
            ),
        ),
    ]
