# Generated by Django 4.2.4 on 2023-08-18 21:26

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ("user_module", "0008_alter_qualificationinfo_years_of_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_group",
            field=models.IntegerField(
                choices=[
                    (100, "User"),
                    (200, "Hub Admin"),
                    (300, "Chapter Admin"),
                    (400, "Staff Admin"),
                    (500, "Super Admin"),
                ],
                default=100,
                verbose_name="User Group",
            ),
        ),
    ]
