# Generated by Django 4.2.4 on 2023-08-19 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ("user_module", "0009_alter_user_user_group"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="qualificationinfo",
            options={"verbose_name": "Skill", "verbose_name_plural": "Skills"},
        ),
        migrations.RemoveField(
            model_name="qualificationinfo",
            name="certifications",
        ),
        migrations.RemoveField(
            model_name="qualificationinfo",
            name="cv",
        ),
        migrations.RemoveField(
            model_name="qualificationinfo",
            name="employment_status",
        ),
        migrations.RemoveField(
            model_name="qualificationinfo",
            name="skills",
        ),
        migrations.RemoveField(
            model_name="qualificationinfo",
            name="years_of_experience",
        ),
        migrations.AddField(
            model_name="profileinfo",
            name="employment_status",
            field=models.CharField(
                blank=True,
                max_length=200,
                verbose_name="Current Employment Status",
            ),
        ),
        migrations.AddField(
            model_name="qualificationinfo",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Skills"
            ),
        ),
        migrations.AlterField(
            model_name="qualificationinfo",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills_info",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="CertificationsInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Certification Name",
                    ),
                ),
                (
                    "certificate",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="Scholar_certifications",
                        verbose_name="Certifications",
                    ),
                ),
                (
                    "date_acquired",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date Certification Achieved",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssociationsInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Association Name",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Association Role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="associations_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Association",
                "verbose_name_plural": "Associations",
            },
        ),
    ]
