# Generated by Django 4.2.4 on 2023-08-19 22:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_module", "0010_alter_qualificationinfo_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalinfo",
            name="cv",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="CV"
            ),
        ),
    ]
