# Generated by Django 4.2.4 on 2023-08-20 07:48

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ("user_module", "0011_personalinfo_cv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="associationsinfo",
            name="role",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Role in Association",
            ),
        ),
    ]
