# Generated by Django 4.2.4 on 2023-08-20 09:23

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ("user_module", "0013_alter_qualificationinfo_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skillsinfo",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Skill"
            ),
        ),
    ]
