# Generated by Django 4.2.4 on 2023-08-20 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ("user_module", "0014_alter_skillsinfo_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skillsinfo",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills_info",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
