# Generated by Django 4.2.4 on 2023-08-20 09:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_module", "0015_alter_skillsinfo_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="QualificationInfo",
        ),
    ]
