# Generated by Django 4.2.4 on 2023-08-20 10:56

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ("user_module", "0016_delete_qualificationinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificationsinfo",
            name="certificate_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Certification URL"
            ),
        ),
    ]
