# Generated by Django 4.2.4 on 2023-08-22 07:50

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ("user_module", "0018_alter_certificationsinfo_certificate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="scholar_level",
        ),
        migrations.AddField(
            model_name="profileinfo",
            name="scholar_level",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                verbose_name="Scholar Education Level",
            ),
        ),
    ]
