# Generated by Django 4.2.4 on 2023-08-22 08:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_module", "0020_alter_profileinfo_employment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personalinfo",
            name="cv",
        ),
        migrations.AddField(
            model_name="profileinfo",
            name="cv",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="CV"
            ),
        ),
    ]
