# Generated by Django 4.2.4 on 2023-08-28 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_module", "0021_remove_personalinfo_cv_profileinfo_cv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educationinfo",
            name="graduation_year",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1984)],
                verbose_name="Year of Graduation",
            ),
        ),
        migrations.AlterField(
            model_name="educationinfo",
            name="year_of_study",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Year of Study"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="scholar_type",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "ELP"), (2, "WTF"), (3, "Both")],
                null=True,
                verbose_name="Scholar Type",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_group",
            field=models.PositiveIntegerField(
                choices=[
                    (100, "User"),
                    (200, "Hub Admin"),
                    (300, "Chapter Admin"),
                    (400, "Staff Admin"),
                    (500, "Super Admin"),
                ],
                default=100,
                verbose_name="User Group",
            ),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="PF",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workexperienceinfo",
            name="number_of_employees",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Number of Employees"
            ),
        ),
    ]
