# Generated by Django 4.2.4 on 2023-08-18 21:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventattendees",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="eventattendees",
            unique_together={("event", "attendee")},
        ),
    ]
