# Generated by Django 4.2.4 on 2023-08-27 14:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_alter_eventattendees_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventattendees",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Event Attendee",
                "verbose_name_plural": "Event Attendees",
            },
        ),
    ]
