# Generated by Django 4.2.4 on 2023-08-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_alter_eventattendees_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="registered_attendees_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="To Attend"
            ),
        ),
    ]
