# Generated by Django 4.2.4 on 2023-08-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_alter_event_registered_attendees_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_capacity",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
