# Generated by Django 4.2.4 on 2023-08-18 22:06

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Department"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Departments",
            },
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "company",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("posted_on", models.DateField()),
                ("application_deadline", models.DateField()),
                (
                    "description",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                (
                    "opportunity_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="JD Link"
                    ),
                ),
                (
                    "opportunity_requirements",
                    models.CharField(
                        max_length=255, verbose_name="Required Skills"
                    ),
                ),
                ("total_applications", models.IntegerField(default=0)),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunity_department",
                        to="opportunities.department",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Opportunities",
                "ordering": ("-posted_on",),
            },
        ),
        migrations.CreateModel(
            name="OpportunityApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resume",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="CV",
                    ),
                ),
                (
                    "cover_letter",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Cover Letter",
                    ),
                ),
                (
                    "certificate",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Certificate",
                    ),
                ),
                ("applied_on", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Applied", "Applied"),
                            ("Received", "Received"),
                            ("Shortlisted", "Shortlisted"),
                            ("Rejected", "Rejected"),
                            ("Selected", "Selected"),
                            ("Offered", "Offered"),
                        ],
                        default="Applied",
                        max_length=255,
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="opportunities.opportunity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "opportunity")},
            },
        ),
    ]
