# Generated by Django 4.2.4 on 2023-08-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="total_applications",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
